---
service: reading-list-redirect
runtime: go116
env_variables:
  UNUSED: unused
  # Modify to override the default and point to a real server.
  # READING_LIST_SERVER: "http://localhost:8080/entries"
handlers:
  # Method handlers: direct to script
  - url: /add
    script: auto
    secure: always
  - url: /.+
    static_dir: static
    secure: always
  - url: /$
    static_files: static/index.html
    secure: always
    upload: static
